repos:
  - repo: local
    hooks:
      - id: gofmt
        name: gofmt
        entry: sh -c "gofmt -s -w ."
        language: system
        files: \.go$
      - id: goimports
        name: goimports
        entry: goimports -w .
        language: system
        files: \.go$
      - id: golangci-lint
        name: golangci-lint
        entry: golangci-lint run
        pass_filenames: false
        language: system
        files: \.go$